### ISSUE TITLE
404 link on homepage

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/staging.julialang.org#1]
"C implementation"

https://github.com/JuliaLang/julia/blob/master/test/perf/micro/perf.c#L126

no longer works. I could make a PR to non-master 0.6, or do you want to link to the new "benchmark" repository that was excised?

**Comment by ararslan** [comment]
This issue should have been opened against https://github.com/JuliaLang/julialang.github.com. See https://github.com/JuliaLang/julialang.github.com/pull/757.
