### ISSUE TITLE
Editors to add

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/staging.julialang.org#2]
We definitely want Jupyter/Jupyterlab in the editors.

**Comment by quinnj** [comment]
Also note that the Sublime-IJulia plugin has been unmaintained for several years now (by me 😅 ); I'm not sure if people are still using it or if it even still works w/ recent versions of julia.

**Comment by ViralBShah** [comment]
Perfect. Maybe we can replace that one with Jupyter then. :-)
