### ISSUE TITLE
Ecosystem slide design

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/staging.julialang.org#4]
@essenciary Do you think we can update the Visualization pane to have 3 parts? A picture, some code that produces it, and text? 

The feedback was that we should show some code fragments, and this seems like the best place to do it.

**Comment by essenciary** [comment]
@ViralBShah Sure -- I'm not sure it will fit, but we can give it a try.

**Comment by ViralBShah** [comment]
What if we make that section a bit taller?

**Comment by essenciary** [comment]
@ViralBShah Let me try something quickly. We definitely need space for the code, we can't show it in a 1/3 of that container. So yes, let's try the section taller, with code under the image and text.

**Comment by essenciary** [comment]
Code pushed
