### ISSUE TITLE
Ecosystems content

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/staging.julialang.org#5]
For the Ecosystems content, I need some help. I need:

1. A picture/plot
2. Some code
3. Explanatory text

May I request:
@StefanKarpinski For the General slide
@quinnj for Data Science
@ChrisRackauckas For Scientific domain
@simonbyrne for mathematics
@andreasnoack for computing (parallel)

This is the biggest missing thing to complete the new website design.

**Comment by ViralBShah** [comment]
@ranjanan is helping put this together.

**Comment by ranjanan** [comment]
#7
